name: Lobby
version: 1.0
main: fr.doritanh.olurwa.lobby.Lobby
api-version: 1.16

commands:
   help:
      description: Affiche de l'aide
      usage: /<command>
      permission: lobby.command.help
        
permissions:
   lobby.command.help:
      description: Authorise le /help
      default: op
   lobby.commands.bypass:
      description: Affiche toutes les suggestions
      default: op
   lobby.*:
      description: Tout le plugin lobby
      default: op
      children:
         lobby.command.help: true
         lobby.commands.bypass: true